version: "3.4"

services:
  vocalia.account:
    image: ${DOCKER_REGISTRY-}vocaliaaccount
    build:
      context: .
      dockerfile: src\apis\Vocalia.Account\Dockerfile
    ports:
      - 9000:9000
  vocalia.editor:
    image: ${DOCKER_REGISTRY-}vocaliaeditor
    build:
      context: .
      dockerfile: src\apis\Vocalia.Editor\Dockerfile
    ports:
      - 9001:9001
  vocalia.ingest:
    image: ${DOCKER_REGISTRY-}vocaliaingest
    build:
      context: .
      dockerfile: src\apis\Vocalia.Ingest\Dockerfile
    ports:
      - 9002:9002
  vocalia.social:
    image: ${DOCKER_REGISTRY-}vocaliasocial
    build:
      context: .
      dockerfile: src\apis\Vocalia.Social\Dockerfile
    ports:
      - 9003:9003
  vocalia.podcast:
    image: ${DOCKER_REGISTRY-}vocaliapodcast
    build:
      context: .
      dockerfile: src\apis\Vocalia.Podcast\Dockerfile
    ports:
      - 9004:9004
  vocalia.publishing:
    image: ${DOCKER_REGISTRY-}vocaliapublishing
    build:
      context: .
      dockerfile: src\apis\Vocalia.Publishing\Dockerfile
    ports:
      - 9005:9005
  vocalia.gateway:
    image: ${DOCKER_REGISTRY-}vocaliagateway
    build:
      context: .
      dockerfile: src\apis\Vocalia.Gateway\Dockerfile
    ports:
      - 9006:9006
    depends_on:
      - vocalia.account
      - vocalia.editor
      - vocalia.ingest
      - vocalia.social
      - vocalia.podcast
      - vocalia.publishing


      

