version: '3.4'

services:
  vocalia.gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  vocalia.account:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  vocalia.podcast:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  vocalia.editor:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  vocalia.publishing:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  vocalia.social:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  vocalia.ingest:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
