version: '3.4'

services:
  vocalia.gateway:
    image: ${DOCKER_REGISTRY-}vocaliagateway
    build:
      context: .
      dockerfile: src/services/Vocalia.Gateway/Dockerfile
    depends_on:
      - vocalia.podcast
      - vocalia.social
      - vocalia.ingest
      - vocalia.editor
      - vocalia.publish

  vocalia.podcast:
    image: ${DOCKER_REGISTRY-}vocaliapodcast
    build:
      context: .
      dockerfile: src/apis/Podcast/Vocalia.Podcast/Dockerfile

  vocalia.social:
    image: ${DOCKER_REGISTRY-}vocaliasocial
    build:
      context: .
      dockerfile: src/apis/Social/Vocalia.Social/Dockerfile

  vocalia.ingest:
    image: ${DOCKER_REGISTRY-}vocaliaingest
    build:
      context: .
      dockerfile: src/apis/Ingest/Vocalia.Ingest/Dockerfile

  vocalia.editor:
    image: ${DOCKER_REGISTRY-}vocaliaeditor
    build:
      context: .
      dockerfile: src/apis/Editor/Vocalia.Editor/Dockerfile

  vocalia.publish:
    image: ${DOCKER_REGISTRY-}vocaliapublish
    build:
      context: .
      dockerfile: src/apis/Publishing/Vocalia.Publishing/Dockerfile