version: '3.4'

services:
  vocalia.gateway:
    image: ${DOCKER_REGISTRY-}vocaliagateway
    build:
      context: .
      dockerfile: src/Vocalia.Gateway/Dockerfile

  vocalia.podcast:
    image: ${DOCKER_REGISTRY-}vocaliapodcast
    build:
      context: .
      dockerfile: src/apis/Podcast/Vocalia.Podcast/Dockerfile

