// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Vocalia.Facades.iTunes.DTOs.RSS;
//
//    var welcome = Welcome.FromJson(jsonString);

namespace Vocalia.Facades.iTunes.DTOs
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class EntryPoint
    {
        [JsonProperty("feed")]
        public Feed Feed { get; set; }
    }

    public partial class Feed
    {
        [JsonProperty("author")]
        public Author Author { get; set; }

        [JsonProperty("entry")]
        public Entry[] Entry { get; set; }

        [JsonProperty("updated")]
        public Icon Updated { get; set; }

        [JsonProperty("rights")]
        public Icon Rights { get; set; }

        [JsonProperty("title")]
        public Icon Title { get; set; }

        [JsonProperty("icon")]
        public Icon Icon { get; set; }

        [JsonProperty("link")]
        public Link[] Link { get; set; }

        [JsonProperty("id")]
        public Icon Id { get; set; }
    }

    public partial class Author
    {
    }

    public partial class Entry
    {
        [JsonProperty("im:name")]
        public Icon ImName { get; set; }

        [JsonProperty("im:price")]
        public ImPrice ImPrice { get; set; }

        [JsonProperty("im:image")]
        public ImImage[] ImImage { get; set; }

        [JsonProperty("summary")]
        public Icon Summary { get; set; }

        [JsonProperty("im:artist")]
        public ImArtist ImArtist { get; set; }

        [JsonProperty("title")]
        public Icon Title { get; set; }

        [JsonProperty("link")]
        public Link Link { get; set; }

        [JsonProperty("id")]
        public Id Id { get; set; }

        [JsonProperty("im:contentType")]
        public ImContentType ImContentType { get; set; }

        [JsonProperty("category")]
        public Category Category { get; set; }

        [JsonProperty("im:releaseDate")]
        public ImReleaseDate ImReleaseDate { get; set; }

        [JsonProperty("rights", NullValueHandling = NullValueHandling.Ignore)]
        public Icon Rights { get; set; }
    }

    public partial class Category
    {
        [JsonProperty("attributes")]
        public CategoryAttributes Attributes { get; set; }
    }

    public partial class CategoryAttributes
    {
        [JsonProperty("im:id")]
        public long ImId { get; set; }

        [JsonProperty("term")]
        public string Term { get; set; }

        [JsonProperty("scheme")]
        public Uri Scheme { get; set; }

        [JsonProperty("label")]
        public string Label { get; set; }
    }

    public partial class Id
    {
        [JsonProperty("label")]
        public Uri Label { get; set; }

        [JsonProperty("attributes")]
        public IdAttributes Attributes { get; set; }
    }

    public partial class IdAttributes
    {
        [JsonProperty("im:id")]
        public long ImId { get; set; }
    }

    public partial class ImArtist
    {
        [JsonProperty("label")]
        public string Label { get; set; }

        [JsonProperty("attributes", NullValueHandling = NullValueHandling.Ignore)]
        public ImArtistAttributes Attributes { get; set; }
    }

    public partial class ImArtistAttributes
    {
        [JsonProperty("href")]
        public Uri Href { get; set; }
    }

    public partial class ImContentType
    {
        [JsonProperty("attributes")]
        public ImContentTypeAttributes Attributes { get; set; }
    }

    public partial class ImContentTypeAttributes
    {
        [JsonProperty("term")]
        public string Term { get; set; }

        [JsonProperty("label")]
        public string Label { get; set; }
    }

    public partial class ImImage
    {
        [JsonProperty("label")]
        public Uri Label { get; set; }

        [JsonProperty("attributes")]
        public ImImageAttributes Attributes { get; set; }
    }

    public partial class ImImageAttributes
    {
        [JsonProperty("height")]
        public long Height { get; set; }
    }

    public partial class Icon
    {
        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore)]
        public string Label { get; set; }
    }

    public partial class ImPrice
    {
        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore)]
        public string Label { get; set; }

        [JsonProperty("attributes", NullValueHandling = NullValueHandling.Ignore)]
        public ImPriceAttributes Attributes { get; set; }
    }

    public partial class ImPriceAttributes
    {
        [JsonProperty("amount")]
        public long Amount { get; set; }

        [JsonProperty("currency")]
        public string Currency { get; set; }
    }

    public partial class ImReleaseDate
    {
        [JsonProperty("label")]
        public DateTimeOffset Label { get; set; }

        [JsonProperty("attributes")]
        public Icon Attributes { get; set; }
    }

    public partial class Link
    {
        [JsonProperty("attributes")]
        public LinkAttributes Attributes { get; set; }
    }

    public partial class LinkAttributes
    {
        [JsonProperty("rel")]
        public string Rel { get; set; }

        [JsonProperty("type", NullValueHandling = NullValueHandling.Ignore)]
        public string Type { get; set; }

        [JsonProperty("href")]
        public Uri Href { get; set; }
    }
   
}
